/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewclearRouteImport } from './routes/newclear'
import { Route as IndexRouteImport } from './routes/index'

const NewclearRoute = NewclearRouteImport.update({
  id: '/newclear',
  path: '/newclear',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/newclear': typeof NewclearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/newclear': typeof NewclearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/newclear': typeof NewclearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/newclear'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/newclear'
  id: '__root__' | '/' | '/newclear'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewclearRoute: typeof NewclearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/newclear': {
      id: '/newclear'
      path: '/newclear'
      fullPath: '/newclear'
      preLoaderRoute: typeof NewclearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewclearRoute: NewclearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
